### ISSUE TITLE
Problem with poetry install

### ISSUE THREAD

**Issue by msolal** [aramis-lab/clinicadl#371]
When installing ClinicaDL in developer mode using `poetry` (version 1.3.2), itself installed with `pipx` (version 1.1.0), the `poetry install` command leads to the following error: 
<img width="1137" alt="Screenshot 2023-02-08 at 15 19 43" src="https://user-images.githubusercontent.com/56113310/217586419-6492f44c-1340-4097-92aa-16c1c76b46f3.png">
<img width="882" alt="Screenshot 2023-02-08 at 15 19 51" src="https://user-images.githubusercontent.com/56113310/217586387-652a34a8-14f9-49fa-a86a-abcd6b3639ef.png">

**Comment by ravih18** [comment]
Hello @msolal 

Thanks for reporting this bug, it looks like this is because of the keyring of the machine you are trying to install ClinicaDL. 
This can be solved by adding the following variable to your `.bashrc`: `export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring`.

As this cannot be solved in this repo, I close this issue.

Ravi
