### ISSUE TITLE
Spaces are not in English and will cause errors during runtime

### ISSUE THREAD

**Issue by CCF0211** [aramis-lab/clinicadl#79]
In clinicadl_env/lib/python3.6/site-packages/clinica/utils/ux.py, line 21
cprint("\t%s | %s" % (unique_participants[-1], sessions_last_participant))
The first space in "\t%s | %s"  is not in English, it will cause an error during runtime:
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 17: ordinal not in range(128)

**Comment by alexandreroutier** [comment]
Hi @CC0624,

Thank your for spotting this issue. @14thibea made a PR in https://github.com/aramis-lab/clinica/pull/105 to solve this solve. We will make a new release next days so that this issue so that this issue will disappear.

In the meantime, you can modify manually `clinicadl_env/lib/python3.6/site-packages/clinica/utils/ux.py ` and remove non-breaking spaces you mentionned. You should be able to run ClinicaDL :)

Thanks again,
Alex

PS: We will close this issue once new version of Clinica will be released.

**Comment by alexandreroutier** [comment]
Hi,

With the recent release of ClinicaDL, this issue can be closed.

Thanks again for your feedback,
Alex
